### ISSUE TITLE
포트폴리오 json 데이터가 안 받아와지는 경우가 있음

### ISSUE THREAD

**Issue by kourindou** [kpuce2022CD/Centum#32]
포트폴리오 작성 후 포트폴리오를 볼 때 포트폴리오 내용을 담은 json데이터가 안 받아 와지는 경우가 있습니다.

**Comment by hedwig3798** [comment]
데이터베이스의 최신화가 되지 않아서 생긴 문제입니다.

데이터베이스 최신화 후 정상작동 되는것 확인했습니다
